import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../ai/providers/daily_plan_provider.dart';
import '../../ai/models/daily_plan.dart';
import '../widgets/ai_generating_animation.dart';
import '../widgets/task_card.dart';
import 'daily_plan_edit_page.dart';

class DailyPlanPage extends ConsumerWidget {
  const DailyPlanPage({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final planAsync = ref.watch(dailyPlanNotifierProvider());

    return Scaffold(
      appBar: AppBar(
        title: const Text('Today\'s Plan'),
        actions: [
          // Edit button (only show when plan exists)
          planAsync.maybeWhen(
            data: (plan) {
              if (plan != null) {
                return IconButton(
                  icon: const Icon(Icons.edit),
                  onPressed: () {
                    Navigator.of(context).push(
                      MaterialPageRoute(
                        builder: (context) => DailyPlanEditPage(plan: plan),
                      ),
                    );
                  },
                  tooltip: 'Edit Plan',
                );
              }
              return const SizedBox.shrink();
            },
            orElse: () => const SizedBox.shrink(),
          ),
          IconButton(
            icon: const Icon(Icons.refresh),
            onPressed: () {
              ref.read(dailyPlanNotifierProvider().notifier).generatePlan();
            },
            tooltip: 'Regenerate Plan',
          ),
        ],
      ),
      body: planAsync.when(
        loading: () => const AIGeneratingAnimation(),
        error: (error, stack) => _buildErrorState(context, ref, error),
        data: (plan) {
          if (plan == null) {
            return _buildEmptyState(context, ref);
          }
          return _buildPlanView(context, ref, plan);
        },
      ),
    );
  }

  Widget _buildPlanView(BuildContext context, WidgetRef ref, DailyPlan plan) {
    return Column(
      children: [
        // Header with theme & quote
        Container(
          padding: const EdgeInsets.all(16),
          color: Theme.of(context).colorScheme.primaryContainer,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  const Icon(Icons.auto_awesome, size: 20),
                  const SizedBox(width: 8),
                  Expanded(
                    child: Text(
                      plan.dailyTheme,
                      style: Theme.of(context).textTheme.titleMedium?.copyWith(
                            fontWeight: FontWeight.bold,
                          ),
                    ),
                  ),
                ],
              ),
              if (plan.motivationalQuote != null) ...[
                const SizedBox(height: 12),
                Row(
                  children: [
                    const Icon(Icons.format_quote, size: 16),
                    const SizedBox(width: 4),
                    Expanded(
                      child: Text(
                        plan.motivationalQuote ?? '',
                        style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                              fontStyle: FontStyle.italic,
                            ),
                      ),
                    ),
                  ],
                ),
              ],
              const SizedBox(height: 8),
              Text(
                'Generated by AI • ${plan.tasks.length} tasks',
                style: Theme.of(context).textTheme.bodySmall?.copyWith(
                      color: Colors.grey.shade700,
                    ),
              ),
            ],
          ),
        ),

        // Task list
        Expanded(
          child: ListView.builder(
            padding: const EdgeInsets.all(16),
            itemCount: plan.tasks.length,
            itemBuilder: (context, index) {
              final task = plan.tasks[index];
              return TaskCard(
                task: task,
                onComplete: () {
                  ref
                      .read(dailyPlanNotifierProvider().notifier)
                      .markTaskComplete(task.id);
                },
              );
            },
          ),
        ),

        // Stats footer
        _buildStatsFooter(context, plan),
      ],
    );
  }

  Widget _buildStatsFooter(BuildContext context, DailyPlan plan) {
    final completedCount = plan.tasks.where((t) => t.isCompleted).length;
    final totalDuration = plan.tasks.fold<int>(
      0,
      (sum, task) => sum + task.estimatedDuration,
    );

    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.grey.shade100,
        border: Border(top: BorderSide(color: Colors.grey.shade300)),
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: [
          _StatChip(
            icon: Icons.check_circle,
            label: 'Completed',
            value: '$completedCount/${plan.tasks.length}',
          ),
          _StatChip(
            icon: Icons.access_time,
            label: 'Total Time',
            value: '${totalDuration ~/ 60}h ${totalDuration % 60}m',
          ),
        ],
      ),
    );
  }

  Widget _buildEmptyState(BuildContext context, WidgetRef ref) {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(Icons.auto_awesome, size: 64, color: Colors.grey.shade400),
          const SizedBox(height: 16),
          Text(
            'No plan for today',
            style: Theme.of(context).textTheme.titleLarge,
          ),
          const SizedBox(height: 8),
          Text(
            'Let AI generate a personalized plan for you',
            style: Theme.of(context).textTheme.bodyMedium,
          ),
          const SizedBox(height: 24),
          ElevatedButton.icon(
            onPressed: () {
              ref.read(dailyPlanNotifierProvider().notifier).generatePlan();
            },
            icon: const Icon(Icons.auto_awesome),
            label: const Text('Generate Plan'),
            style: ElevatedButton.styleFrom(
              padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildErrorState(BuildContext context, WidgetRef ref, Object error) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(24),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(Icons.error_outline, size: 64, color: Colors.red.shade400),
            const SizedBox(height: 16),
            Text(
              'Failed to generate plan',
              style: Theme.of(context).textTheme.titleLarge,
            ),
            const SizedBox(height: 8),
            Text(
              error.toString(),
              style: Theme.of(context).textTheme.bodySmall,
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 24),
            ElevatedButton(
              onPressed: () {
                ref.read(dailyPlanNotifierProvider().notifier).generatePlan();
              },
              child: const Text('Retry'),
            ),
          ],
        ),
      ),
    );
  }
}

class _StatChip extends StatelessWidget {
  final IconData icon;
  final String label;
  final String value;

  const _StatChip({
    required this.icon,
    required this.label,
    required this.value,
  });

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Icon(icon, size: 24),
        const SizedBox(height: 4),
        Text(label, style: const TextStyle(fontSize: 12)),
        Text(value, style: const TextStyle(fontWeight: FontWeight.bold)),
      ],
    );
  }
}
